"""Create the RAW extractor metadata space in CDF."""

from __future__ import annotations

import os
from pathlib import Path

try:
    from dotenv import load_dotenv  # type: ignore
except ImportError:  # pragma: no cover - optional dependency
    load_dotenv = None

from cognite.client import CogniteClient
from cognite.client.config import ClientConfig
from cognite.client.credentials import OAuthClientCredentials
from cognite.client.data_classes.data_modeling.spaces import SpaceApply


def _load_env_file() -> None:
    """Load environment variables from .env if dotenv is available."""

    env_path = Path(".env")
    if load_dotenv is not None:
        load_dotenv(dotenv_path=env_path if env_path.exists() else None)
        return

    if not env_path.exists():
        return

    for line in env_path.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip())


def main() -> None:
    _load_env_file()

    required = [
        "CDF_HOST",
        "CDF_PROJECT",
        "CDF_CLIENT_ID",
        "CDF_CLIENT_SECRET",
        "CDF_TOKEN_URL",
    ]
    missing = [key for key in required if not os.getenv(key)]
    if missing:
        raise SystemExit(f"Missing required environment variables: {missing}")

    credentials = OAuthClientCredentials(
        token_url=os.environ["CDF_TOKEN_URL"],
        client_id=os.environ["CDF_CLIENT_ID"],
        client_secret=os.environ["CDF_CLIENT_SECRET"],
        scopes=["user_impersonation"],
    )
    client = CogniteClient(
        ClientConfig(
            client_name="plex-space-bootstrap",
            base_url=os.environ["CDF_HOST"],
            project=os.environ["CDF_PROJECT"],
            credentials=credentials,
        )
    )

    space_name = os.getenv("PLEX_EXTRACTOR_SPACE", "plex_extractor_runs")
    space = SpaceApply(
        space=space_name,
        name=space_name.replace("_", " ").title(),
        description="Operational nodes generated by Plex RAW extractors",
    )
    client.data_modeling.spaces.apply(space)
    print(f"Space '{space_name}' applied successfully.")


if __name__ == "__main__":
    main()
